INSERT INTO interests (interest_name) VALUES ('Bieganie');
INSERT INTO interests (interest_name) VALUES ('Jazda na rowerze');
INSERT INTO interests (interest_name) VALUES ('Pływanie');
INSERT INTO interests (interest_name) VALUES ('Wspinaczka');
INSERT INTO interests (interest_name) VALUES ('Fotografia');
INSERT INTO interests (interest_name) VALUES ('Gotowanie');
INSERT INTO interests (interest_name) VALUES ('Czytanie książek');
INSERT INTO interests (interest_name) VALUES ('Gra na gitarze');
INSERT INTO interests (interest_name) VALUES ('Podróże');
INSERT INTO interests (interest_name) VALUES ('Wędkarstwo');
INSERT INTO interests (interest_name) VALUES ('Ogrodnictwo');
INSERT INTO interests (interest_name) VALUES ('Majsterkowanie');
INSERT INTO interests (interest_name) VALUES ('Gry planszowe');
INSERT INTO interests (interest_name) VALUES ('Gry komputerowe');
INSERT INTO interests (interest_name) VALUES ('Malowanie');
INSERT INTO interests (interest_name) VALUES ('Rysowanie');
INSERT INTO interests (interest_name) VALUES ('Szydełkowanie');
INSERT INTO interests (interest_name) VALUES ('Robienie na drutach');
INSERT INTO interests (interest_name) VALUES ('Taniec');
INSERT INTO interests (interest_name) VALUES ('Joga');
INSERT INTO interests (interest_name) VALUES ('Kolekcjonerstwo');
INSERT INTO interests (interest_name) VALUES ('Wolontariat');
INSERT INTO interests (interest_name) VALUES ('Nauka języków obcych');
INSERT INTO interests (interest_name) VALUES ('Programowanie');
INSERT INTO interests (interest_name) VALUES ('Pisanie');
INSERT INTO interests (interest_name) VALUES ('Gra na pianinie');
INSERT INTO interests (interest_name) VALUES ('Kaligrafia');
INSERT INTO interests (interest_name) VALUES ('Origami');
INSERT INTO interests (interest_name) VALUES ('Rzeźbiarstwo');
INSERT INTO interests (interest_name) VALUES ('Ceramika');
INSERT INTO interests (interest_name) VALUES ('Jazda konna');
INSERT INTO interests (interest_name) VALUES ('Narciarstwo');
INSERT INTO interests (interest_name) VALUES ('Snowboard');
INSERT INTO interests (interest_name) VALUES ('Żeglarstwo');
INSERT INTO interests (interest_name) VALUES ('Nurkowanie');
INSERT INTO interests (interest_name) VALUES ('Gra w szachy');
INSERT INTO interests (interest_name) VALUES ('Medytacja');
INSERT INTO interests (interest_name) VALUES ('Tworzenie biżuterii');
INSERT INTO interests (interest_name) VALUES ('Słuchanie podcastów');
INSERT INTO interests (interest_name) VALUES ('Górskie wędrówki');