DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS profile_interest CASCADE;
DROP TABLE IF EXISTS interests;
DROP TABLE IF EXISTS offers;
DROP TABLE IF EXISTS  body_parameter;
CREATE TABLE IF NOT EXISTS users
(
    id
             BIGSERIAL
        PRIMARY
            KEY,
    role
             varchar(20)  not null,
    username varchar(50)  not null unique,
    email    varchar(100) not null,
    password varchar(255) not null
);


CREATE TABLE IF NOT EXISTS profiles
(
    id
                BIGSERIAL
                             NOT
                                 NULL,
    name
                VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    city        VARCHAR(255) NOT NULL,
    age         INT          NOT NULL,
    user_id     BIGINT       NOT NULL,
    CONSTRAINT pk_profiles PRIMARY KEY
        (
         id
            )
);
CREATE TABLE IF NOT EXISTS interests
(
    id
        BIGSERIAL
                            NOT
                                NULL,
    interest_name
        VARCHAR(150) UNIQUE NOT NULL,
    CONSTRAINT pk_interests PRIMARY KEY
        (
         id
            )
);
CREATE TABLE IF NOT EXISTS profile_interest
(
    profile_id  BIGINT NOT NULL,
    interest_id BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS offers
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    description    TEXT                                    NOT NULL,
    price_per_hour numeric                                 NOT NULL,
    profile_id     BIGINT,
    CONSTRAINT pk_offers PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS body_parameter
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    height  DOUBLE PRECISION,
    weight  DOUBLE PRECISION,
    profile_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_body_parameter PRIMARY KEY (id)
);

ALTER TABLE body_parameter
    ADD CONSTRAINT uc_body_parameter_profile UNIQUE (profile_id);

ALTER TABLE body_parameter
    ADD CONSTRAINT FK_BODY_PARAMETER_ON_profile FOREIGN KEY (profile_id) REFERENCES profiles (id);
ALTER TABLE offers
    ADD CONSTRAINT FK_OFFERS_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profiles (id);
ALTER TABLE profiles
    ADD CONSTRAINT uc_profiles_user UNIQUE (user_id);

ALTER TABLE profiles
    ADD CONSTRAINT FK_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE profile_interest
    ADD CONSTRAINT fk_intpro_on_interest FOREIGN KEY (interest_id) REFERENCES interests (id);

ALTER TABLE profile_interest
    ADD CONSTRAINT fk_intpro_on_profile FOREIGN KEY (profile_id) REFERENCES profiles (id);


CREATE INDEX idx_profiles_user_id ON profiles (user_id);


CREATE INDEX idx_profiles_city ON profiles (city);




